### ISSUE TITLE
Gadgets and hardware: Introduction to Programming Small Devices, Nov 23

### ISSUE THREAD

**Issue by SaraMahallati** [UofTCoders/Events#128]
We will be introduced to the Arduino open source microcontroller development system and build a device using the Adafruit ESP8266 Feather Huzzah [https://www.adafruit.com/product/2821], a postage stamp sized 80MHz WiFi computer with stackable peripherals (called 'Wings'), that uses 1/2 Watt.

**Where**: BL520 (http://map.utoronto.ca/utsg/building/006A)
**When**: November 23, 6-7:30pm
**Instructor**: @bksutherland
**What to bring**: Your laptop (more will be posted closer to the date if needed)

**Comment by linamnt** [comment]
Hi Everyone, this event has **limited space** so if you're interested in attending, it will be first come first served basis via email to uoftcoders@gmail.com with the subject line **"Gadgets and Hardware RSVP"**. We will reply to let you know if you have a spot. 

Thanks in advance, and note that this event is NOT held in MP408. It will be held in BL520 (Claude T Bissell Building 5th floor (http://map.utoronto.ca/utsg/building/006A)

**Comment by bksutherland** [comment]
Hello, All:
Here are the session notes to browse through, see you in BL520 at 6.


B. Sutherland

[Programming_Small_Devices.pdf](https://github.com/UofTCoders/Events/files/1499008/Programming_Small_Devices.pdf)

**Comment by mbonsma** [comment]
If you're using your own computer, download the Arduino IDE from https://www.arduino.cc/

**Comment by joelostblom** [comment]
@bksutherland Thanks so much for leading this workshop, it was fantastic! Inspired by yesterday's event and in the spirit of black Friday, I am on the hunt for a microcontroller starter kit. Do you have one that you would recommend? You mentioned that the upgraded version of the ones we used yesterday were still pretty cheap, is that a good place to start?

**Comment by bksutherland** [comment]
Hi, Joel:

It's feather friday at Adafruit -
https://blog.adafruit.com/2017/11/24/this-black-friday-its-feather-friday-at-adafruit-use-the-code-thankafruit-to-get-20-off-feathers-and-15-off-items-storewide-2/

You may want to consider ordering directly!

https://www.adafruit.com/feather

As I said, ESP32 Huzzah is the faster version of the ESP8266 Huzzah in
Feather form.   It has an ultralow power co-processor so it can monitor
sensor readings in deep sleep mode and trigger a wake up when an event
occurs.   Haven't tried that feature yet, though.   The software install is
a bit more involved, but you strike me as an advanced user.

https://www.adafruit.com/product/3405
https://github.com/bksutherland/ESP32/commit/811a4ce84d635d0f61c570c3f6ba9e1d77a51c22

You'll probably want a set of stacking headers, to allow you to plug it
into the solderless breadboard, and also a wing on top.

For wings -
- Adalogger one is great because an SD adds a lot of storage, and it makes
all the data portable, you just pull it out of the Feather and stick it
into a laptop.
- OLED display is also pretty great - someone designed a Tetris game for it
and it's on Github.   It is, however, breakable, handle carefully.
- Packet radio is interesting because it gives very long range WiFi
- I'd like to try the Mp3 player one, it's new

If you are considering making your creation portable maybe also a LiPoly
battery, because the feather format has a battery recharger.  Or there's
also a container that you can put 3 AA batteries in, that plugs in to the
Feather.  If you are going battery powered you'll want to experiment with
all the deep sleep modes of the board, this can save huge amounts of power
over long monitoring applications.

Sparkfun is also a good store to order from, and Pololu has the best DC-DC
buck/boost regulators (probably not required for what you are doing, but I
need them for intermittent energy sources).

Creatron on College is a great place to shop, although they are usually
lagging behind in stocking Adafruit's new products by about 6 months.   The
ESP32s haven't appeared yet there, for example.

Glad you and the others enjoyed the workshop!  Hope I'll be able to make
the one about Quantum computing.

Best wishes,


~ Brian

**Comment by joelostblom** [comment]
Perfect! Thanks for the detailed response @bksutherland! I will look into buying one this afternoon, fun! =)
