### ISSUE TITLE
Lightning Demos: Show us your academic workflows - June 23

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#54]
Quick demos on the different software, tools and techniques presenters use in their own academic workflows. 

**Where**: MP408
**When**: June 23rd, 2016 6:10pm

**Comment by dcwalk** [comment]
I was probably gonna create a slide and then go into demo. Should I just link to materials here?

**Comment by QuLogic** [comment]
Last time we put a few of the materials in to the repo, but if you're mostly doing a demo (like I did for IPython), then there may not be any need for it. Just linking here would be fine.

**Comment by dcwalk** [comment]
Here is a small deck for my demo tonight: ["Collaborative Writing Workflow"](https://docs.google.com/presentation/d/1-kb1ho8icIaoqCn2Yqg7Nn8B_TtOMU5FkjWdKp1d8LI/edit?usp=sharing)

**Comment by joelostblom** [comment]
_Sorry, this became longer than expected. The TL;DR is that [Authorea](https://www.authorea.com) looks like a promising writing tool and I wanted to share in case it helps someone else!_

Inspired by the workflow presentations last Thursday (thanks for sharing!), I started digging after ways to improve my scholarly workflow again. Currently, my writing routine most often involves using vim (with the [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) [plugins](https://github.com/vim-pandoc/vim-pandoc-syntax)) to write markdown and convert to pdf with pandoc. Everyone else in my lab uses MS Word or Google Docs, so when we collaborate, it is usually all in Google Docs.

My ideal setup would allow me to write in markdown and my collaborators to contribute comments and changes via a WYSIWYG interface. I would then be able to view their feedback through a file version history or some markup syntax (such as [CriticMarkup](http://criticmarkup.com/)).

I looked into ShareLatex, Overleaf, StackEdit and Prose, but non of them provide a full WYSIWYG interface and most are lacking in the way feedback is handled in my opinion. I then revisited a tool called [Authorea](https://www.authorea.com), which turns out to have improved significantly since I tried it last. I just wanted to share some of its biggest advantages in my view, in case it could be a good match for someone else:

- Syncs to one of your GitHub repositories.
- Allows writing to be done in Markdown, Latex or HTML. All articles are rendered in a WYSIWYG interface online.
- If you just want someone to leave comments on your article in the nicely formatted web view, you can create a public URL to share with them. For editing access, they are required to create and Authorea account (but not set up git or anything like that).
- Comments are shown in a side panel like Google Docs, and the commented section is cited in the comment (but not highlighted in the text).
- You can have 1-3 private articles and sync them with your [private student repositories](https://education.github.com/pack) on GitHub (in the manuscript needs to be private).
- There is support for interactive HTML figures and Jupyter Notebooks! All of which can be contained in the same Git repo as your Authorea documents.
- They support citations via bibtex, inline searching of pubmed/crossref/DOI, and dragn drop from Mendeley/Zotero/Endnote.

There are two caveats holding me back from running around and converting everyone in lab to Authorea:
- There is no track changes feature that is intuitive for people used to MS Word/Google Docs. When I chatted with the staff, they said there are big changes to the track changes web interface inbound this summer, so I am looking forward to that!
- Once a new text cell/block has been created, the chosen text format cannot be changed. This is a pity, since it means that collaborators still need to be familiar with the format you have chosen. There are icons for "bold", "cite", "heading" and so on, but it is not as seamless as it could be. Commenting can still be done on the WYSIWYG rendered HTML page, it is just editing of the text that suffers. Again, their staff said that this was something they are working on, but not as immediate as the track changes features.

Since many people seemed to use Latex, here are a few links on Latex in Authorea:

- [How is Authorea different from ShareLaTeX and Overleaf?](https://www.authorea.com/users/3/articles/108532/_show_article)
- [Which LaTeX packages are implemented in Authorea?](https://www.authorea.com/users/77723/articles/111127/_show_article)
- [How to Write Power LaTeX in Authorea](https://www.authorea.com/users/5713/articles/28015/_show_article)
- [A cheat sheet for web friendly latex](https://www.authorea.com/users/3/articles/6868/_show_article)

**Comment by lwjohnst86** [comment]
Thanks @joelostblom for that info! I think it's really useful! Do you mind if I put this up on the website?

**Comment by joelostblom** [comment]
I am happy you found it helpful! Go ahead and put it on the website, just
keep in mind that I have not used Authorea for a long period of time, so
there might be issues I haven't encountered yet.

**Comment by dcwalk** [comment]
@joelostblom hey thanks for this breakdown of Authorea -- this is awesome! Especially will keep my eyes on it in the next few months around the track changes.
I think my ideal case is similar to what you've identified. With everyone's comments I'm gonna retool my stuff again, but probably focus more on the snapshots via .txts from Google Docs for now.

**Comment by joelostblom** [comment]
You're welcome!
I just remembered one additional minor annoyance with Authorea. The comments made on the online article view are not synced to any file in the GitHub repo, they seem to only be accessible via the website. I added that to my description above.
