### ISSUE TITLE
Intro to Git and the Philosophy of Version Control - Jan 11

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#79]
Learn how to take advantage of version control for your projects why it can be useful. We will be focusing on Git, a popular piece of software that does version control. This session is geared towards complete beginners - if you've never touched Git before, this is for you!

**Where**: MP408
**When**: Wednesday, January 11th, 6:10pm
**Preparation**: Bring a laptop with Git installed (see instructions below). Optional: make an account on [GitHub](https://github.com/join?source=header-home). It's free! 
### Git

Installation instructions for Git can be found on the [Git download site](https://git-scm.com/book/en/Getting-Started-Installing-Git)
- On Windows: Download the `.exe` file from this
  [Github link](https://msysgit.github.io) and run it.
- On Mac: To use the graphical Git installer, download from this
  [SourceForge link](https://sourceforge.net/projects/git-osx-installer/)
- On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

**Comment by mbonsma** [comment]
Live stream is [here](https://www.youtube.com/watch?v=51DekMGjzi0).

**Comment by joelostblom** [comment]
@lwjohnst86 @QuLogic On my question yesterday of how much storage git uses. I just found out about `git gc`, which you may already know about, but I will share here in case anyone finds it useful.

In essence (from the [git book](https://git-scm.com/book/en/v2/Git-Internals-Packfiles)):
> The initial format in which Git saves objects on disk is called a “loose” object format. However, occasionally Git packs up several of these objects into a single binary file called a “packfile” in order to save space and be more efficient. Git does this if you have too many loose objects around, if you run the git gc command manually, or if you push to a remote server. 

And from the `git gc` man page:
> Users are encouraged to run this task on a regular basis within each repository to maintain good disk space utilization and good operating performance.

I ran it on a repo with ~75 commits, where the entire repo was ~6 MB and out of that `.git/` was ~5 MB. It trimmed the `.git` directory down to ~600 KB, quite impressive!

I also tried cloning that repo from Github before trimming. As indicated in the git book excerpt, the 4.4 MB that were trimmable with `git gc` were never pushed to Github, because the `.git/` directory was only 600 KB directly after cloning.

So, `git gc` seems to be an effective and safe (based on what I quoted above, I have only used it once...) option to minimize git local storage space. Apparently, `git gc` runs automatically when there are too many loose objects around, but running it manually is still encouraged.

---
Additional info
- http://stackoverflow.com/questions/55729/how-often-should-you-use-git-gc
- http://stackoverflow.com/questions/5709687/what-are-the-loose-objects-that-the-git-gui-refers-to#5710039

**Comment by lwjohnst86** [comment]
Thanks @joelostblom I did not know about this! Learned something :smile:
