### ISSUE TITLE
Opening up your Data - March 1

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/Events#86]
An overview of open data practices and principles. Learn about what it means to work open!

**Where**: Rm 408 on the 4th floor of [Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316)
**When**: Wednesday, March 1st, 6:10pm
**Instructor**:  @derekhoward
**What to bring**: TBD

**Comment by derekhoward** [comment]
I was thinking of leading a discussion session and prepared some slides for context on definitions and why opening your data can be beneficial. I made use of the [Mozilla open data instructor guide](https://mozillascience.github.io/open-data-guides/) and [open data primers](https://mozillascience.github.io/open-data-primers/).

The slides so far can be viewed [here](https://docs.google.com/presentation/d/1NKDz_69uzX2AiUN9FlEFP0FaLYNSP8_gg5IY40Fd8hw/edit?usp=sharing).

If we want to move on to more of the "how" of opening up your data there is also a great set of resources created by Mozilla for [developing a data reuse checklist](https://mozillascience.github.io/open-data-primers/). Definitely a great set of resources that we could expand upon and touch on more in-depth in future sessions.

Last, I've been reading through Bill Mills [blog](http://billmills.github.io/blog/) which is full of insightful posts. If the topic of open data is of interest to you, I'd suggest you take a look.

I know this doesn't follow the usual lesson format (no code!) so let me know if you think I should prepare another document (and what kind of format would be best) for the lessons folder.

**Comment by mbonsma** [comment]
Some things we talked about:

* Tri-agency (i.e. NSERC, CIHR, SSHRC) policy on data: [Data Management Policy](http://www.science.gc.ca/eic/site/063.nsf/eng/h_83F7624E.html?OpenDocument) and [Open Access Policy](http://www.science.gc.ca/eic/site/063.nsf/eng/h_F6765465.html?OpenDocument)
* "[Differential privacy](https://www.wired.com/2016/06/apples-differential-privacy-collecting-data/)" as a way to anonymize sensitive data. 
* Sometimes you can't release your data because of ethics rules (i.e. human data)

**Comment by derekhoward** [comment]
Thanks for the updates on those different topics we mentioned!

One kind of related topic I mentioned was related to genetic non-discrimination and new legislation surrounding it.
I mentioned [this discussion](https://www.youtube.com/watch?v=Q_q_m6qlDzY&) from the Agenda on TVO which might be interesting to some.
